Not Found: /app2/
Traceback (most recent call last):
  File "/home/mzarka/quotes_app/passenger_wsgi.py", line 1, in <module>
    from base.wsgi import application
  File "/home/mzarka/quotes_app/base/__init__.py", line 1, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Traceback (most recent call last):
  File "/home/mzarka/quotes_app/passenger_wsgi.py", line 1, in <module>
    from base.wsgi import application
  File "/home/mzarka/quotes_app/base/__init__.py", line 1, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Traceback (most recent call last):
  File "/home/mzarka/quotes_app/passenger_wsgi.py", line 1, in <module>
    from base.wsgi import application
  File "/home/mzarka/quotes_app/base/__init__.py", line 1, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Internal Server Error: /tnm/
Traceback (most recent call last):
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 560, in resolve
    for pattern in self.url_patterns:
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mzarka/virtualenv/uKKU2_TNM/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python36/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'base'
